# Generated by Django 4.2.5 on 2023-09-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Rод чата в телеграм', null=True, verbose_name='код чата в телеграм'),
        ),
    ]
