# Generated by Django 4.2.5 on 2023-09-23 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, help_text='Место выполнения привычки', max_length=150, null=True, verbose_name='место')),
                ('time_habit', models.TimeField(blank=True, default='12:00', help_text='Время повторения привычки', null=True, verbose_name='время')),
                ('action', models.CharField(help_text='Действие привычки', max_length=200, verbose_name='действие')),
                ('pleasant', models.BooleanField(default=False, help_text='Признак приятной привычки', verbose_name='Признак приятной привычки')),
                ('frequency', models.IntegerField(blank=True, default=1, help_text='Периодичность (в днях)', null=True, verbose_name='Периодичность ')),
                ('award', models.CharField(blank=True, help_text='Вознаграждение за выполнение привычки', max_length=150, null=True, verbose_name='Вознаграждение ')),
                ('duration', models.IntegerField(default=60, help_text='Время на выполнение (в секундах)', verbose_name='Время на выполнение ')),
                ('public_habit', models.BooleanField(default=False, help_text='Признак публичности привычки', verbose_name='Признак публичности')),
                ('next_habit', models.ForeignKey(blank=True, help_text='Связанная приятная привычка', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_habit', to='habits.habit', verbose_name='Связанная привычка')),
                ('user', models.ForeignKey(blank=True, help_text='Владелец привычки', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
