# Generated by Django 4.2.5 on 2023-09-28 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_mailing', models.DateTimeField(auto_now_add=True, verbose_name='дата и время рассылки')),
                ('ok', models.BooleanField(default=True, help_text='успешная или нет отправка', verbose_name='статус')),
                ('result', models.CharField(blank=True, help_text='информация о пересланном сообщении или ошибке', max_length=500, null=True, verbose_name='результат')),
                ('error_code', models.PositiveIntegerField(blank=True, help_text='код ошибки. Заполняется, если возникла ошибка', null=True, verbose_name='код ошибки')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_log', to='habits.habit', verbose_name='привычка')),
            ],
            options={
                'verbose_name': 'Запись журнала рассылки',
                'verbose_name_plural': 'Журнал рассылок',
                'ordering': ['-datetime_mailing'],
            },
        ),
    ]
