# Generated by Django 4.2.5 on 2023-09-30 06:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_mailinglog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='duration',
            field=models.IntegerField(default=60, help_text='Время на выполнение (в секундах)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)], verbose_name='Время на выполнение '),
        ),
    ]
