# Generated by Django 3.2.12 on 2023-09-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'наличные'), ('non-cash', 'перевод на счет')], default='non-cash', max_length=150, verbose_name='способ оплаты'),
        ),
    ]
