# Generated by Django 3.2.12 on 2023-09-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_pay',
            field=models.DateField(auto_now_add=True, verbose_name='дата оплаты'),
        ),
    ]
