# Generated by Django 3.2.12 on 2023-09-03 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_payment_date_pay'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-date_pay',), 'verbose_name': 'оплата', 'verbose_name_plural': 'оплата'},
        ),
    ]
